services:
  jeeves:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jeeves
    restart: unless-stopped
    stop_grace_period: 10s
    stop_signal: SIGTERM
    init: true
    env_file:
      - .env
    environment:
      - PYTHONPATH=/jeeves
      - PYTHONUNBUFFERED=1
    networks:
      - traefik-public
    volumes:
      - ./logs:/jeeves/logs
    healthcheck:
      test: ["CMD", "python", "-c", "import os; os.kill(1, 0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  traefik-public:
    external: true
