name: Deploy Bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup deployment files
        run: |
          ls -la

          # Create .env file
          cat << EOF > sales_bot/.env
          BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          ADMIN_TELEGRAM_ID=${{ secrets.ADMIN_TELEGRAM_ID }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          EOF

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy and configure
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          # Deploy files
          rsync -avz --delete ./sales_bot $DEPLOY_USER@$DEPLOY_HOST:~/
          rsync -avz --delete requirements.txt $DEPLOY_USER@$DEPLOY_HOST:~/sales_bot/
          ssh $DEPLOY_USER@$DEPLOY_HOST 'ls -la /home/sales_bot'
          # Setup environment
          ssh $DEPLOY_USER@$DEPLOY_HOST '
            sudo useradd -m -s /bin/bash sales_bot || true &&
            sudo mkdir -p /var/log/sales_bot &&
            sudo chown -R sales_bot:sales_bot /var/log/sales_bot /home/sales_bot &&
            ls -la &&
            cd /home/sales_bot &&
            ls -la &&
            sudo -u sales_bot python3 -m venv venv &&
            sudo -u sales_bot venv/bin/pip install -r requirements.txt &&
            sudo tee /etc/systemd/system/sales_bot.service << EOF
          [Unit]
          Description=Sales Bot
          After=network.target postgresql.service

          [Service]
          Type=simple
          User=sales_bot
          WorkingDirectory=/home/sales_bot
          ExecStart=/home/sales_bot/venv/bin/python main.py
          StandardOutput=append:/var/log/sales_bot/app.log
          StandardError=append:/var/log/sales_bot/error.log
          Restart=always
          RestartSec=10

          [Install]
          WantedBy=multi-user.target
          EOF'

      - name: Start service
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          ssh $DEPLOY_USER@$DEPLOY_HOST '
            sudo systemctl daemon-reload &&
            sudo systemctl enable sales_bot &&
            sudo systemctl restart sales_bot &&
            sudo systemctl status sales_bot &&
            tail -n 50 /var/log/sales_bot/error.log'
