name: Deploy Bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Create sales_bot user
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          ssh $DEPLOY_USER@$DEPLOY_HOST '
            sudo useradd -m -s /bin/bash sales_bot || true'

      - name: Setup log directory
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          ssh $DEPLOY_USER@$DEPLOY_HOST '
            sudo mkdir -p /var/log/sales_bot &&
            sudo chown -R sales_bot:sales_bot /var/log/sales_bot'

      - name: Deploy application files
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          ssh $DEPLOY_USER@$DEPLOY_HOST 'sudo mkdir -p /home/sales_bot'
          rsync -avz --delete ./sales_bot $DEPLOY_USER@$DEPLOY_HOST:/home/sales_bot
          rsync -avz --delete requirements.txt $DEPLOY_USER@$DEPLOY_HOST:/home/sales_bot/
          ssh $DEPLOY_USER@$DEPLOY_HOST 'sudo chown -R sales_bot:sales_bot /home/sales_bot'

      - name: Setup Python environment
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          ssh $DEPLOY_USER@$DEPLOY_HOST '
            cd /home/sales_bot &&
            sudo -u sales_bot python3 -m venv venv &&
            sudo -u sales_bot venv/bin/pip install -r requirements.txt &&
            sudo -u sales_bot venv/bin/pip install pytest'

      - name: Run tests
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          ssh $DEPLOY_USER@$DEPLOY_HOST '
            cd /home/sales_bot/sales_bot &&
            sudo -u sales_bot ../venv/bin/pytest tests/ &&
            if [ $? -ne 0 ]; then
              echo "Tests failed! Aborting deployment." &&
              exit 1
            fi'

      - name: Configure systemd service
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          ssh $DEPLOY_USER@$DEPLOY_HOST 'sudo tee /etc/systemd/system/sales_bot.service << EOF
          [Unit]
          Description=Sales Bot
          After=network.target postgresql.service

          [Service]
          Type=simple
          User=sales_bot
          WorkingDirectory=/home/sales_bot/sales_bot
          Environment="API_ID=${{ secrets.ENV_API_ID }}"
          Environment="API_HASH=${{ secrets.ENV_API_HASH }}"
          Environment="BOT_TOKEN=${{ secrets.ENV_BOT_TOKEN }}"
          Environment="ADMIN_TELEGRAM_ID=${{ secrets.ENV_ADMIN_TELEGRAM_ID }}"
          Environment="OPENROUTER_API_KEY=${{ secrets.ENV_OPENROUTER_API_KEY }}"
          Environment="DATABASE_URL=${{ secrets.ENV_DATABASE_URL }}"
          Environment="LOG_LEVEL=INFO"
          Environment="LOG_FILE=/var/log/sales_bot/app.log"
          ExecStart=/home/sales_bot/venv/bin/python main.py
          StandardOutput=append:/var/log/sales_bot/app.log
          StandardError=append:/var/log/sales_bot/error.log
          Restart=always
          RestartSec=10

          [Install]
          WantedBy=multi-user.target
          EOF'

      - name: Start and verify service
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          ssh $DEPLOY_USER@$DEPLOY_HOST '
            echo "Reloading systemd..." &&
            sudo systemctl daemon-reload &&

            echo "\nEnabling and starting service..." &&
            sudo systemctl enable sales_bot &&
            sudo systemctl restart sales_bot &&

            echo "\nWaiting for service to stabilize..." &&
            sleep 10 &&

            echo "\nChecking service status..." &&
            sudo systemctl status sales_bot &&

            echo "\nChecking if service is active..." &&
            if ! sudo systemctl is-active --quiet sales_bot; then
              echo "Service failed to start!" &&
              echo "\nLast 50 lines of error log:" &&
              sudo tail -n 50 /var/log/sales_bot/error.log &&
              echo "\nJournal logs:" &&
              sudo journalctl -u sales_bot -n 50 --no-pager &&
              exit 1
            fi &&

            echo "\nService started successfully!" &&
            echo "\nRecent application logs:" &&
            sudo tail -n 20 /var/log/sales_bot/app.log &&

            echo "\nRecent error logs:" &&
            sudo tail -n 20 /var/log/sales_bot/error.log'
