name: Deploy Bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create project structure
        run: |
          mkdir -p sales_bot/{bot,db,utils}
          touch sales_bot/config.py
          touch sales_bot/main.py
          touch sales_bot/bot/{__init__.py,commands.py,dialogs.py,gpt.py}
          touch sales_bot/db/{__init__.py,models.py,queries.py}
          touch sales_bot/utils/{__init__.py,export.py,logging.py}

      - name: Create .env file
        run: |
          cat << EOF > sales_bot/.env
          # Telegram Bot settings
          BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          API_ID=${{ secrets.API_ID }}
          API_HASH=${{ secrets.API_HASH }}
          ADMIN_TELEGRAM_ID=${{ secrets.ADMIN_TELEGRAM_ID }}

          # OpenRouter
          OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}

          # Database settings
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          EOF

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Create directories and set permissions
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          ssh $DEPLOY_USER@$DEPLOY_HOST '
          sudo useradd -m -s /bin/bash sales_bot || true
          sudo mkdir -p /var/log/sales_bot
          sudo chown -R sales_bot:sales_bot /var/log/sales_bot'

      - name: Deploy application
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          rsync -avz --delete \
            --exclude '.git' \
            --exclude 'venv' \
            --exclude '__pycache__' \
            ./sales_bot/ $DEPLOY_USER@$DEPLOY_HOST:/home/sales_bot/sales_bot/

      - name: Set up Python environment
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          ssh $DEPLOY_USER@$DEPLOY_HOST '
          cd /home/sales_bot/sales_bot && \
          sudo -u sales_bot python3 -m venv venv && \
          sudo -u sales_bot venv/bin/pip install -r requirements.txt'

      - name: Configure service
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          ssh $DEPLOY_USER@$DEPLOY_HOST 'sudo tee /etc/systemd/system/sales_bot.service << EOF
          [Unit]
          Description=Sales Bot
          After=network.target postgresql.service

          [Service]
          Type=simple
          User=sales_bot
          Group=sales_bot
          WorkingDirectory=/home/sales_bot/sales_bot
          Environment=PYTHONUNBUFFERED=1
          ExecStart=/home/sales_bot/sales_bot/venv/bin/python main.py
          StandardOutput=append:/var/log/sales_bot/app.log
          StandardError=append:/var/log/sales_bot/error.log
          Restart=always
          RestartSec=10

          [Install]
          WantedBy=multi-user.target
          EOF'

      - name: Set permissions and restart service
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          ssh $DEPLOY_USER@$DEPLOY_HOST '
          sudo chown -R sales_bot:sales_bot /home/sales_bot/sales_bot
          sudo systemctl daemon-reload
          sudo systemctl enable sales_bot
          sudo systemctl restart sales_bot'

      - name: Check service status and logs
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          ssh $DEPLOY_USER@$DEPLOY_HOST '
          sudo systemctl status sales_bot
          tail -n 50 /var/log/sales_bot/error.log'
